name: Update members wall

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-members-wall

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate members mural
        uses: crystal-actions/contributor-mural@v1.3.0
        with:
          config: .github/contributor-mural.yml
          token: ${{ github.token }}
          commit_message: "Update members wall"
